/*
 * func-name: sub_37D3E
 * func-address: 0x37d3e
 * callers: 0x25bf4
 * callees: 0x37324, 0x37b8c, 0x37c9c, 0x3f236, 0x3f2f0, 0x3f3c8, 0x3f46b, 0x3f48b, 0x3fca9, 0x3fe5f, 0x3fe7f, 0x3fea7, 0x3ff35, 0x4007b, 0x400cc
 */

int sub_37D3E()
{
  int env; // eax
  int env_1; // ebx
  struct tm *timeptr; // eax
  int v4; // eax
  int env_2; // eax
  char v6[16]; // [esp+0h] [ebp-10h] BYREF

  sub_37B8C();
  dword_54174 = 0;
  dword_54170 = 0;
  env = getenv(aAilDebug);                      // "AIL_DEBUG"
  env_1 = env;
  if ( !env )
    return sub_3FCA9(env);
  if ( getenv(aAilSysDebug) )                   // "AIL_SYS_DEBUG"
    dword_54170 = 1;
  env = fopen(env_1, (int)aWT);                 // "w+t"
  ::env = env;
  if ( !env )
    return sub_3FCA9(env);
  if ( isatty(*(_DWORD *)(env + 16)) )
    setbuf(::env, 0);
  time(v6);
  timeptr = (struct tm *)putchar(v6);
  v4 = asctime(timeptr);
  strcpy(byte_5417C, v4);
  byte_54194 = 0;
  fprintf(::env, "-------------------------------------------------------------------------------\n");// "-------------------------------------------------------------------------------\n"
  fprintf(::env, "Audio Interface Library application usage script generated by AIL V%s\n", a302);// "3.02"
  fprintf(::env, "Start time: %s\n", byte_5417C);
  env_2 = fprintf(::env, "-------------------------------------------------------------------------------\n\n");
  sub_3FCA9(env_2);
  n99 = 0;
  n59 = 0;
  n59_0 = 0;
  n99_0 = 0;
  dword_54158 = sub_3F236(p_sub_37C30);
  sub_3F3C8(dword_54158, 100);
  sub_3F2F0(dword_54158);
  dword_54174 = 1;
  dword_54178 = 1;
  sub_37C9C();
  dword_54178 = 0;
  return fprintf(::env, "AIL_startup()\n");
}
